//
//  constants.cpp
//  final-project-sherina0922
//
//  Created by Sherina Hung on 4/23/18.
//

#include <stdio.h>

#define INITIAL_VIEW_DISTANCE 150
#define CONSTANT_CIRCLE_RESOLUTION 50
#define GRABBER_X 320
#define GRABBER_Y 240
#define FRAME_RATE 60
#define FULL_COLOR 255
#define WIDTH 41
#define HEIGHT 21
#define CUBE_SIZE 5.0
#define GRAY 63.0
#define SIZE 21
#define CHARS_IN_MAZE 441
#define HALF 0.5
#define DEFAULT_DPI 72
#define DEFAULT_FONT_SIZE 24

#define MAX_TIME 150000.0
#define INITIAL_RADIUS 100
#define UNICODE_1 49
#define MILLIS_TO_SEC 1000
#define DECREASE_RADIUS 1
#define TRANSLATE_MONSTER_STATS_Y 100
#define MEDIUM_DAMAGE_PERCENTAGE 0.85
#define LOW_DAMAGE_PERCENTAGE 0.75
#define BATTLE_OFFSET_X 130
#define BATTLE_OFFSET_Y 50

#define MAZE_TRANSLATE 100
#define DECREASE_VISIBILITY 3
#define MIN_VISIBILITY 2
#define INITIAL_VISIBILITY 5

#define TIMER_LOCATION 20
#define TIMER_HEIGHT 10
#define UNICODE_0 48
#define UNICODE_9 57

#define OFFSET_X 10
#define CHARACTER_INFO_Y 70
#define PI_OVER_FOUR M_PI/4
#define CAMERA_STYLUS_INNER 2
#define CAMERA_STYLUS_OUTER 5
#define CAMERA_MODE_SIGN_Y 70
#define CHOOSE_MODE_OFFSET_X 100
#define CHOOSE_MODE_OFFSET_Y 17
#define CHOOSE_CHARACTER_OFFSET_X 250
#define CHOOSE_CHARACTER_OFFSET_Y 40

